### ISSUE TITLE
kitchen-azurerm fails with chefdk 3.1.0 

### ISSUE THREAD

**Issue by kikitux** [test-kitchen/kitchen-azurerm#94]
Hello.

I am new to checkdk and kitchen, but seems I can't get to work kitchen-azurerm with the latest chefdk.

My host is macos.

I did install 3.10, then did `chef gem install kitchen-azurerm` 

However any command fails with error, found kitchen.log, with this error:

```
0  (master) $ cat .kitchen/logs/kitchen.log
E, [2018-08-04T23:42:15.884646 #71281] ERROR -- Kitchen: ------Exception-------
E, [2018-08-04T23:42:15.884746 #71281] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2018-08-04T23:42:15.884769 #71281] ERROR -- Kitchen: Message: Could not load the 'azurerm' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
E, [2018-08-04T23:42:15.884799 #71281] ERROR -- Kitchen: ----------------------
E, [2018-08-04T23:42:15.884813 #71281] ERROR -- Kitchen: ------Backtrace-------
E, [2018-08-04T23:42:15.884826 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/driver.rb:48:in `rescue in for_plugin'
E, [2018-08-04T23:42:15.884840 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/driver.rb:37:in `for_plugin'
E, [2018-08-04T23:42:15.884854 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:234:in `new_driver'
E, [2018-08-04T23:42:15.884868 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:247:in `new_instance'
E, [2018-08-04T23:42:15.884882 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:142:in `block in build_instances'
E, [2018-08-04T23:42:15.884896 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:141:in `map'
E, [2018-08-04T23:42:15.884910 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:141:in `with_index'
E, [2018-08-04T23:42:15.884924 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:141:in `build_instances'
E, [2018-08-04T23:42:15.884937 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:117:in `instances'
E, [2018-08-04T23:42:15.884951 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2018-08-04T23:42:15.884965 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2018-08-04T23:42:15.884979 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command/list.rb:30:in `call'
E, [2018-08-04T23:42:15.884992 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/cli.rb:52:in `perform'
E, [2018-08-04T23:42:15.885006 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/cli.rb:120:in `list'
E, [2018-08-04T23:42:15.885020 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
E, [2018-08-04T23:42:15.885034 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
E, [2018-08-04T23:42:15.885048 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
E, [2018-08-04T23:42:15.885061 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
E, [2018-08-04T23:42:15.885075 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/bin/kitchen:13:in `block in <top (required)>'
E, [2018-08-04T23:42:15.885089 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2018-08-04T23:42:15.885102 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/bin/kitchen:13:in `<top (required)>'
E, [2018-08-04T23:42:15.885116 #71281] ERROR -- Kitchen: /usr/local/bin/kitchen:272:in `load'
E, [2018-08-04T23:42:15.885129 #71281] ERROR -- Kitchen: /usr/local/bin/kitchen:272:in `<main>'
E, [2018-08-04T23:42:15.885155 #71281] ERROR -- Kitchen: ----End Backtrace-----
E, [2018-08-04T23:42:15.885170 #71281] ERROR -- Kitchen: ---Nested Exception---
E, [2018-08-04T23:42:15.885183 #71281] ERROR -- Kitchen: Class: Gem::ConflictError
E, [2018-08-04T23:42:15.885197 #71281] ERROR -- Kitchen: Message: Unable to activate azure_mgmt_network-0.17.0, because ms_rest_azure-0.10.8 conflicts with ms_rest_azure (~> 0.11.0)
E, [2018-08-04T23:42:15.885211 #71281] ERROR -- Kitchen: ----------------------
E, [2018-08-04T23:42:15.885224 #71281] ERROR -- Kitchen: ------Backtrace-------
E, [2018-08-04T23:42:15.885237 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/driver.rb:48:in `rescue in for_plugin'
E, [2018-08-04T23:42:15.885251 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/driver.rb:37:in `for_plugin'
E, [2018-08-04T23:42:15.885265 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:234:in `new_driver'
E, [2018-08-04T23:42:15.885278 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:247:in `new_instance'
E, [2018-08-04T23:42:15.885292 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:142:in `block in build_instances'
E, [2018-08-04T23:42:15.885306 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:141:in `map'
E, [2018-08-04T23:42:15.885319 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:141:in `with_index'
E, [2018-08-04T23:42:15.885333 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:141:in `build_instances'
E, [2018-08-04T23:42:15.885346 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/config.rb:117:in `instances'
E, [2018-08-04T23:42:15.885360 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2018-08-04T23:42:15.885374 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2018-08-04T23:42:15.885387 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command/list.rb:30:in `call'
E, [2018-08-04T23:42:15.885401 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/cli.rb:52:in `perform'
E, [2018-08-04T23:42:15.885414 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/cli.rb:120:in `list'
E, [2018-08-04T23:42:15.885428 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
E, [2018-08-04T23:42:15.885480 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
E, [2018-08-04T23:42:15.885494 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
E, [2018-08-04T23:42:15.885508 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
E, [2018-08-04T23:42:15.885522 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/bin/kitchen:13:in `block in <top (required)>'
E, [2018-08-04T23:42:15.885535 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2018-08-04T23:42:15.885549 #71281] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/bin/kitchen:13:in `<top (required)>'
E, [2018-08-04T23:42:15.885563 #71281] ERROR -- Kitchen: /usr/local/bin/kitchen:272:in `load'
E, [2018-08-04T23:42:15.885588 #71281] ERROR -- Kitchen: /usr/local/bin/kitchen:272:in `<main>'
E, [2018-08-04T23:42:15.885602 #71281] ERROR -- Kitchen: ----End Backtrace-----
0  (master) $ 
```

If I check the versions, I can see are 2 installed, but what's failing is not picking the right one
```
0  (master) $ chef gem list | grep azure
azure_mgmt_network (0.17.0)
azure_mgmt_resources (0.17.0, 0.16.0)
kitchen-azurerm (0.14.3)
ms_rest_azure (0.11.0, 0.10.8)
0  (master) $
```

Any hint is welcome.

thanks!
Alvaro.

**Comment by jcoeltjen** [comment]
Have you tried removing the azure_mgmt_* gems and kitchen-azurerm and then reinstall the driver?

**Comment by kikitux** [comment]
Hello

thanks both for the update, somehow i missed @jcoeltjen update.

I reinstalled, but same issue, and i am not very familiar with the gems commands, so as for now i noticed that chefdk 2.5.13 works with kitchen-azurerm and thats good enough for me.

i will try next chefdk version.

thanks everyone for your time here.
